# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "QirLabeledFormatter",
]

@typing.final
class QirLabeledFormatter:
    def test(self) -> builtins.int: ...

