name: Test PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
    tests:
      runs-on: ubuntu-latest
      steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                # Checkout the merge commit to include changes from both the base and the head of the PR
                ref: refs/pull/${{ github.event.pull_request.number }}/merge
                sparse-checkout: |
                    .github
                    pyproject.toml
                    src
                    uv.lock
            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                # Uses the latest python version allowed by the project's constraints.
                python-version-file: pyproject.toml

            - name: Install uv
              uses: astral-sh/setup-uv@v7
              with:
              # Install a specific version of uv.
                version: '0.11.2'
                enable-cache: true
                cache-dependency-glob: |
                  **/uv.lock
                  **/pyproject.toml

            - name: Audit dependencies
              run: |
                uv run src/scripts/audit_dependencies.sh

            - name: Install dev dependencies
              run: |
                uv sync --locked --all-groups

            - name: Run ci_checks.sh script, if it's present
              run: test ! -f src/scripts/ci_checks.sh || uv run src/scripts/ci_checks.sh

            - name: Test qir-formatter with pytest
              run: |
                uv run pytest src/tests

            - name: Upload pytest test results
              uses: actions/upload-artifact@v4
              with:
                name: pytest-results
                path: src/qir_formatter/htmlcov
